CREATE TABLE v3_0_early_vote_sites(id INTEGER PRIMARY KEY,
                                   name TEXT,
                                   address_location_name TEXT,
                                   address_line1 TEXT,
                                   address_line2 TEXT,
                                   address_line3 TEXT,
                                   address_city TEXT,
                                   address_state TEXT,
                                   address_zip TEXT,
                                   directions TEXT,
                                   voter_services TEXT,
                                   start_date TEXT,
                                   end_date TEXT,
                                   days_times_open TEXT);
