CREATE TABLE v3_0_contests (id INTEGER PRIMARY KEY,
                            election_id INTEGER,
                            electoral_district_id INTEGER,
                            type TEXT,
                            partisan BOOLEAN CHECK (partisan IN (0,1)),
                            primary_party TEXT,
                            electorate_specifications TEXT,
                            special BOOLEAN CHECK (special IN (0,1)),
                            office TEXT,
                            filing_closed_date DATE,
                            number_elected INTEGER,
                            number_voting_for INTEGER,
                            ballot_id INTEGER,
                            ballot_placement INTEGER);
