#!/bin/sh

docker-compose -f docker-compose-postgres-tests.yml build

docker-compose -f docker-compose-postgres-tests.yml run processor
TEST_EXIT_STATUS=$?

docker-compose -f docker-compose-postgres-tests.yml kill db

exit $TEST_EXIT_STATUS
