CREATE TABLE election_administrations (id BIGINT NOT NULL,
                                       results_id BIGINT REFERENCES results (id) NOT NULL,
                                       PRIMARY KEY (results_id, id),
                                       name TEXT,
                                       eo_id BIGINT,
                                       ovc_id BIGINT,
                                       physical_address_location_name TEXT,
                                       physical_address_line1 TEXT,
                                       physical_address_line2 TEXT,
                                       physical_address_line3 TEXT,
                                       physical_address_city TEXT,
                                       physical_address_state TEXT,
                                       physical_address_zip TEXT,
                                       mailing_address_location_name TEXT,
                                       mailing_address_line1 TEXT,
                                       mailing_address_line2 TEXT,
                                       mailing_address_line3 TEXT,
                                       mailing_address_city TEXT,
                                       mailing_address_state TEXT,
                                       mailing_address_zip TEXT,
                                       elections_url TEXT,
                                       registration_url TEXT,
                                       am_i_registered_url TEXT,
                                       absentee_url TEXT,
                                       where_do_i_vote_url TEXT,
                                       what_is_on_my_ballot_url TEXT,
                                       rules_url TEXT,
                                       voter_services TEXT,
                                       hours TEXT);
