CREATE TABLE contests (id BIGINT NOT NULL,
                       results_id BIGINT REFERENCES results (id) NOT NULL,
                       PRIMARY KEY (results_id, id),
                       election_id BIGINT,
                       electoral_district_id BIGINT,
                       type TEXT,
                       partisan BOOLEAN,
                       primary_party TEXT,
                       electorate_specifications TEXT,
                       special BOOLEAN,
                       office TEXT,
                       filing_closed_date DATE,
                       number_elected BIGINT,
                       number_voting_for BIGINT,
                       ballot_id BIGINT,
                       ballot_placement BIGINT);
