CREATE TABLE sources (id BIGINT NOT NULL,
                      results_id BIGINT REFERENCES results (id) NOT NULL,
                      PRIMARY KEY (results_id, id),
                      name TEXT,
                      vip_id TEXT,
                      datetime DATE,
                      description TEXT,
                      organization_url TEXT,
                      feed_contact_id BIGINT,
                      tou_url TEXT);
