CREATE TABLE referendums (id BIGINT NOT NULL,
                          results_id BIGINT REFERENCES results (id) NOT NULL,
                          PRIMARY KEY (results_id, id),
                          title TEXT,
                          subtitle TEXT,
                          brief TEXT,
                          text TEXT,
                          pro_statement TEXT,
                          con_statement TEXT,
                          passage_threshold TEXT,
                          effect_of_abstain TEXT);
