CREATE TABLE candidates (id INTEGER NOT NULL,
                         results_id INTEGER REFERENCES results (id) NOT NULL,
                         PRIMARY KEY (results_id, id),
                         name TEXT,
                         party TEXT,
                         candidate_url TEXT,
                         biography TEXT,
                         phone TEXT,
                         photo_url TEXT,
                         filed_mailing_address_location_name TEXT,
                         filed_mailing_address_line1 TEXT,
                         filed_mailing_address_line2 TEXT,
                         filed_mailing_address_line3 TEXT,
                         filed_mailing_address_city TEXT,
                         filed_mailing_address_state TEXT,
                         filed_mailing_address_zip TEXT,
                         email TEXT,
                         sort_order INTEGER);
