CREATE TABLE street_segments (id BIGINT NOT NULL,
                              results_id BIGINT REFERENCES results (id) NOT NULL,
                              PRIMARY KEY (results_id, id),
                              start_house_number INTEGER,
                              end_house_number INTEGER,
                              odd_even_both TEXT,
                              start_apartment_number INTEGER,
                              end_apartment_number INTEGER,
                              non_house_address_house_number INTEGER,
                              non_house_address_house_number_prefix TEXT,
                              non_house_address_house_number_suffix TEXT,
                              non_house_address_street_direction TEXT,
                              non_house_address_street_name TEXT,
                              non_house_address_street_suffix TEXT,
                              non_house_address_address_direction TEXT,
                              non_house_address_apartment TEXT,
                              non_house_address_city TEXT,
                              non_house_address_state TEXT,
                              non_house_address_zip TEXT,
                              precinct_id BIGINT,
                              precinct_split_id BIGINT);
