CREATE TABLE v5_1_party_contests (id TEXT NOT NULL,
                                 results_id BIGINT REFERENCES results (id) NOT NULL,
                                 abbreviation TEXT,
                                 ballot_selection_ids TEXT,
                                 ballot_sub_title TEXT,
                                 ballot_title TEXT,
                                 electoral_district_id TEXT,
                                 electorate_specification TEXT,
                                 external_identifier_type TEXT,
                                 external_identifier_othertype TEXT,
                                 external_identifier_value TEXT,
                                 has_rotation TEXT,
                                 name TEXT,
                                 sequence_order TEXT,
                                 vote_variation TEXT,
                                 other_vote_variation TEXT);
