CREATE TABLE v5_0_sources (id TEXT NOT NULL,
                           results_id BIGINT REFERENCES results (id) NOT NULL,
                           PRIMARY KEY (results_id, id),
                           name TEXT,
                           vip_id TEXT,
                           date_time TEXT,
                           description TEXT,
                           organization_uri TEXT,
                           feed_contact_information_id TEXT,
                           terms_of_use_uri TEXT,
                           version TEXT);

CREATE TABLE v5_0_elections (id TEXT NOT NULL,
                             results_id BIGINT REFERENCES results (id) NOT NULL,
                             PRIMARY KEY (results_id, id),
                             date TEXT,
                             name TEXT,
                             election_type TEXT,
                             state_id TEXT,
                             is_statewide TEXT,
                             registration_info TEXT,
                             absentee_ballot_info TEXT,
                             results_uri TEXT,
                             polling_hours TEXT,
                             has_election_day_registration TEXT,
                             registration_deadline TEXT,
                             absentee_request_deadline TEXT,
                             hours_open_id TEXT);

CREATE TABLE v5_0_states (id TEXT NOT NULL,
                          results_id BIGINT REFERENCES results (id) NOT NULL,
                          PRIMARY KEY (results_id, id),
                          name TEXT,
                          election_administration_id TEXT,
                          external_identifier_type TEXT,
                          external_identifier_othertype TEXT,
                          external_identifier_value TEXT);

CREATE TABLE v5_0_hours_open (id TEXT NOT NULL,
                              results_id BIGINT REFERENCES results(id) NOT NULL,
                              schedule_id TEXT NOT NULL,
                              PRIMARY KEY (results_id, id, schedule_id));

CREATE TABLE v5_0_schedules (id TEXT NOT NULL,
                             results_id BIGINT REFERENCES results (id) NOT NULL,
                             PRIMARY KEY (results_id, id),
                             start_time TEXT,
                             end_time TEXT,
                             start_time2 TEXT,
                             end_time2 TEXT,
                             is_only_by_appointment TEXT,
                             is_or_by_appointment TEXT,
                             is_subject_to_change TEXT,
                             start_date TEXT,
                             end_date TEXT);

CREATE TABLE v5_0_localities (id TEXT NOT NULL,
                              results_id BIGINT REFERENCES results (id) NOT NULL,
                              PRIMARY KEY (results_id, id),
                              name TEXT,
                              state_id TEXT,
                              type TEXT,
                              other_type TEXT,
                              election_administration_id TEXT,
                              external_identifier_type TEXT,
                              external_identifier_othertype TEXT,
                              external_identifier_value TEXT);

CREATE TABLE v5_0_parties (id TEXT NOT NULL,
                           results_id BIGINT REFERENCES results (id) NOT NULL,
                           PRIMARY KEY (results_id, id),
                           abbreviation TEXT,
                           color TEXT,
                           external_identifier_type TEXT,
                           external_identifier_othertype TEXT,
                           external_identifier_value TEXT,
                           logo_uri TEXT,
                           name TEXT);

CREATE TABLE v5_0_people (id TEXT NOT NULL,
                          results_id BIGINT REFERENCES results (id) NOT NULL,
                          PRIMARY KEY (results_id, id),
                          contact_information_id TEXT,
                          date_of_birth TEXT,
                          first_name TEXT,
                          last_name TEXT,
                          middle_name TEXT,
                          nickname TEXT,
                          prefix TEXT,
                          suffix TEXT,
                          title TEXT,
                          profession TEXT,
                          party_id TEXT);

CREATE TABLE v5_0_polling_locations (id TEXT NOT NULL,
                                     results_id BIGINT REFERENCES results (id) NOT NULL,
                                     PRIMARY KEY (results_id, id),
                                     address_line TEXT,
                                     directions TEXT,
                                     hours TEXT,
                                     hours_open_id TEXT,
                                     photo_uri TEXT,
                                     is_drop_box TEXT,
                                     is_early_voting TEXT,
                                     latitude TEXT,
                                     longitude TEXT,
                                     latlng_source TEXT);

CREATE TABLE v5_0_precincts (id TEXT NOT NULL,
                             results_id BIGINT REFERENCES results (id) NOT NULL,
                             PRIMARY KEY (results_id, id),
                             name TEXT,
                             number TEXT,
                             locality_id TEXT,
                             ward TEXT,
                             is_mail_only TEXT,
                             external_identifier_type TEXT,
                             external_identifier_othertype TEXT,
                             external_identifier_value TEXT,
                             precinct_split_name TEXT,
                             ballot_style_id TEXT);

CREATE TABLE v5_0_election_administrations (id TEXT NOT NULL,
                                            results_id BIGINT REFERENCES results (id) NOT NULL,
                                            PRIMARY KEY (results_id, id),
                                            absentee_uri TEXT,
                                            am_i_registered_uri TEXT,
                                            elections_uri TEXT,
                                            registration_uri TEXT,
                                            rules_uri TEXT,
                                            what_is_on_my_ballot_uri TEXT,
                                            where_do_i_vote_uri TEXT);

CREATE TABLE v5_0_departments (id TEXT NOT NULL,
                               results_id BIGINT REFERENCES results (id) NOT NULL,
                               PRIMARY KEY (results_id, id),
                               department_name TEXT,
                               election_administration_id TEXT,
                               contact_information_id TEXT,
                               election_official_person_id TEXT);

CREATE TABLE v5_0_voter_services (id TEXT NOT NULL,
                                  results_id BIGINT REFERENCES results (id) NOT NULL,
                                  PRIMARY KEY (results_id, id),
                                  department_id TEXT,
                                  contact_information_id TEXT,
                                  description TEXT, -- internationalized
                                  election_official_person_id TEXT,
                                  voter_service_type TEXT,
                                  other_type TEXT);

CREATE TABLE v5_0_electoral_districts (id TEXT NOT NULL,
                                       results_id BIGINT REFERENCES results (id) NOT NULL,
                                       PRIMARY KEY (results_id, id),
                                       name TEXT,
                                       type TEXT,
                                       number TEXT,
                                       external_identifier_type TEXT,
                                       external_identifier_othertype TEXT,
                                       external_identifier_value TEXT,
                                       other_type TEXT);


CREATE TABLE v5_0_ballot_measure_contests (id TEXT NOT NULL,
                                           results_id BIGINT REFERENCES results (id) NOT NULL,
                                           PRIMARY KEY (results_id, id),
                                           con_statement TEXT,
                                           effect_of_abstain TEXT,
                                           full_text TEXT,
                                           info_uri TEXT,
                                           passage_threshold TEXT,
                                           pro_statement TEXT,
                                           summary_text TEXT,
                                           type TEXT,
                                           other_type TEXT);

CREATE TABLE v5_0_ballot_selections (id TEXT NOT NULL,
                                     results_id BIGINT REFERENCES results (id) NOT NULL,
                                     PRIMARY KEY (results_id, id),
                                     ballot_measure_contest_id TEXT,
                                     ballot_measure_contest_selection_id TEXT,
                                     text TEXT,
                                     candidate_id TEXT,
                                     endorsement_party_id TEXT,
                                     is_write_in TEXT);

CREATE TABLE v5_0_ballot_styles (id TEXT NOT NULL,
                                 results_id BIGINT REFERENCES results (id) NOT NULL,
                                 PRIMARY KEY (results_id, id),
                                 image_uri TEXT,
                                 ordered_contest_id TEXT,
                                 party_id TEXT);

CREATE TABLE v5_0_candidates (id TEXT NOT NULL,
                              results_id BIGINT REFERENCES results (id) NOT NULL,
                              PRIMARY KEY (results_id, id),
                              ballot_name TEXT,
                              external_identifier_type TEXT,
                              external_identifier_othertype TEXT,
                              external_identifier_value TEXT,
                              file_date TEXT,
                              is_incumbent TEXT,
                              is_top_ticket TEXT,
                              party_id TEXT,
                              person_id TEXT,
                              post_election_status TEXT,
                              pre_election_status TEXT,
                              sequence_order TEXT,
                              contest_id TEXT);

CREATE TABLE v5_0_candidate_contests (id TEXT NOT NULL,
                                      results_id BIGINT REFERENCES results (id) NOT NULL,
                                      PRIMARY KEY (results_id, id),
                                      abbreviation TEXT,
                                      ballot_sub_title TEXT,
                                      ballot_title TEXT,
                                      electoral_district_id TEXT,
                                      electorate_specification TEXT,
                                      external_identifier_type TEXT,
                                      external_identifier_othertype TEXT,
                                      external_identifier_value TEXT,
                                      has_rotation TEXT,
                                      name TEXT,
                                      sequence_order TEXT,
                                      vote_variation TEXT,
                                      other_vote_variation TEXT,
                                      number_elected TEXT,
                                      primary_party_id TEXT,
                                      votes_allowed TEXT,
                                      office_id TEXT);

CREATE TABLE v5_0_candidate_contest_ballot_selections (candidate_contest_id TEXT NOT NULL,
                                                       ballot_selection_id TEXT NOT NULL,
                                                       results_id BIGINT REFERENCES results (id) NOT NULL,
                                                       PRIMARY KEY (results_id, candidate_contest_id, ballot_selection_id));

CREATE TABLE v5_0_contact_information (id TEXT NOT NULL,
                                       results_id BIGINT REFERENCES results (id) NOT NULL,
                                       address_line TEXT,
                                       email TEXT,
                                       fax TEXT,
                                       hours TEXT,
                                       hours_open_id TEXT,
                                       name TEXT,
                                       phone1 TEXT,
                                       phone2 TEXT,
                                       uri TEXT);

CREATE TABLE v5_0_offices (id TEXT NOT NULL,
                           results_id BIGINT REFERENCES results (id) NOT NULL,
                           PRIMARY KEY (results_id, id),
                           contact_information_id TEXT,
                           electoral_district_id TEXT,
                           external_identifier_type TEXT,
                           external_identifier_othertype TEXT,
                           external_identifier_value TEXT,
                           filing_deadline TEXT,
                           is_partisan TEXT,
                           name TEXT,
                           office_holder_person_id TEXT,
                           term_type TEXT,
                           term_start_date TEXT,
                           term_end_date TEXT);

CREATE TABLE v5_0_locality_polling_locations (locality_id TEXT NOT NULL,
                                              polling_location_id TEXT NOT NULL,
                                              results_id BIGINT REFERENCES results (id) NOT NULL,
                                              PRIMARY KEY (results_id, locality_id, polling_location_id));

CREATE TABLE v5_0_precinct_electoral_districts (precinct_id TEXT NOT NULL,
                                                electoral_district_id TEXT NOT NULL,
                                                results_id BIGINT REFERENCES results (id) NOT NULL,
                                                PRIMARY KEY (results_id, precinct_id, electoral_district_id));

CREATE TABLE v5_0_precinct_polling_locations (precinct_id TEXT NOT NULL,
                                              polling_location_id TEXT NOT NULL,
                                              results_id BIGINT REFERENCES results (id) NOT NULL,
                                              PRIMARY KEY (results_id, precinct_id, polling_location_id));

CREATE TABLE v5_0_state_polling_locations (state_id TEXT NOT NULL,
                                           polling_location_id TEXT NOT NULL,
                                           results_id BIGINT REFERENCES results (id) NOT NULL,
                                           PRIMARY KEY (results_id, state_id, polling_location_id));

ALTER TABLE v5_0_street_segments ADD COLUMN unit_number TEXT;
