create table v5_dashboard.localities (
  results_id int,
  id text,
  name text,
  type text,
  error_count int default 0,
  precinct_errors int default 0,
  precinct_count int default 0,
  precinct_completion int default 0,
  polling_location_errors int default 0,
  polling_location_count int default 0,
  polling_location_completion int default 0,
  street_segment_errors int default 0,
  street_segment_count int default 0,
  street_segment_completion int default 0,
  hours_open_errors int default 0,
  hours_open_count int default 0,
  hours_open_completion int default 0,
  election_administration_errors int default 0,
  election_administration_count int default 0,
  election_administration_completion int default 0,
  department_errors int default 0,
  department_count int default 0,
  department_completion int default 0,
  voter_service_errors int default 0,
  voter_service_count int default 0,
  voter_service_completion int default 0);
