CREATE TABLE v5_1_retention_contests (id TEXT NOT NULL,
                                      results_id BIGINT REFERENCES results (id) NOT NULL,
                                      PRIMARY KEY (results_id, id),
                                      abbreviation TEXT,
                                      ballot_selection_ids TEXT,
                                      ballot_sub_title TEXT,
                                      ballot_title TEXT,
                                      electoral_district_id TEXT,
                                      electorate_specification TEXT,
                                      external_identifier_type TEXT,
                                      external_identifier_othertype TEXT,
                                      external_identifier_value TEXT,
                                      has_rotation TEXT,
                                      name TEXT,
                                      sequence_order TEXT,
                                      vote_variation TEXT,
                                      other_vote_variation TEXT,
                                      con_statement TEXT,
                                      effect_of_abstain TEXT,
                                      full_text TEXT,
                                      info_uri TEXT,
                                      passage_threshold TEXT,
                                      pro_statement TEXT,
                                      summary_text TEXT,
                                      type TEXT,
                                      other_type TEXT,
                                      candidate_id TEXT,
                                      office_id TEXT);
