CREATE TABLE v5_0_street_segments (id TEXT NOT NULL,
                                   results_id BIGINT REFERENCES results (id) NOT NULL,
                                   PRIMARY KEY (results_id, id),
                                   address_direction TEXT,
                                   city TEXT,
                                   includes_all_addresses BOOLEAN,
                                   odd_even_both TEXT,
                                   precinct_id TEXT,
                                   start_house_number INTEGER,
                                   end_house_number INTEGER,
                                   state TEXT,
                                   street_direction TEXT,
                                   street_name TEXT,
                                   street_suffix TEXT,
                                   zip TEXT);
